### ISSUE TITLE
Unexpected input(s) 

### ISSUE THREAD

**Issue by umithyo** [SpicyPizza/create-envfile#10]
![image](https://user-images.githubusercontent.com/12802646/106284483-594e2300-6254-11eb-9e5d-3a6426da0435.png)
I'm getting this error with the example provided. Any ideas how to solve it? Am I doing something wrong?

**Comment by davidsarkany** [comment]
I have same issue
https://github.com/davidsarkany/sts-backend/actions/runs/523191085

**Comment by dherbst** [comment]
This is because from https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file

> To pass inputs to the Docker container, you must declare the input using inputs and pass the input in the args keyword.

`inputs` is missing in the file: https://github.com/SpicyPizza/create-envfile/blob/master/action.yml

You can ignore the warning for now.  

One way to avoid the warning is to find a way to pass the values as a defined input - but this would change the way this action works.

**Comment by proftom** [comment]
OK so the problem is because we are using docker? @dherbst, I did not understand what the fix should be, nor your final sentence. Can you please give an example? 

I wanted to use this action so I could create an .env file in the same directory as my app (where my sources and docker files are), just like I would have on my local dev box. Does this action not do this? If so, docker should be irrelevant.

**Comment by dherbst** [comment]
@proftom this is not an error, it is a warning.  You can ignore the warning, the action will work when github runs it because the python file looks for environment variables with `INPUT_` as a prefix.   You can see this here https://github.com/SpicyPizza/create-envfile/blob/master/src/create-envfile.py#L7-L9

> I wanted to use this action so I could create an .env file in the same directory as my app (where my sources and docker files are), just like I would have on my local dev box. Does this action not do this?

The action does this for environment variables you name beginning with: `envkey_` as stated in the https://github.com/SpicyPizza/create-envfile/blob/master/README.md

**Comment by AngelOnFira** [comment]
Hmm I suppose the best course of action for this is to just document the behaviour in the Readme, as it seems that I can't add a wildcard to the expected input. If there are any other suggestions I'd be down to explore alternatives.

**Comment by AustinSpinazze** [comment]
I am also having this issue currently and it does have a warning, but github actions will not allow it to progress any further. Is there something I am doing wrong with the properties I am using?
```- name: Create .env file
        uses: SpicyPizza/create-envfile@v1.1
        with:
            envkey_EMAILJS_USER_ID: ${{secrets.EMAILJS_USER_ID}}
            envkey_EMAILJS_SERVICE_ID : ${{ secrets.EMAILJS_SERVICE_ID }}
            envkey_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
```

**Comment by khannakshat7** [comment]
I am facing issues with creating .env file. I am deploying my project using Google app engine. The project gets deployed but .env file is not created. Can you please help me with the issue.

This is my main.yaml file-
```
name: CI

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
  
jobs:
  create-envfile:
    runs-on: ubuntu-18.04
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: False
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_USER: ${{ secrets.USER }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          file_name: .env

  
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}

      - name: Publish app to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
```
Please check the output at https://github.com/khannakshat7/Elektra/actions/runs/888591866
