### ISSUE TITLE
multiple .env files on different directories

### ISSUE THREAD

**Issue by jonaxd1** [SpicyPizza/create-envfile#11]
~~I'm creating multiple .env but file doesn't appear.~~
When creating multiple .env files in different directories, doesn't get directory specified and overrides on all steps.

~~Only gets a warning~~
`Warning: Unexpected input(s) 'envkey_DOCKER_WEB_PORT', 'envkey_DOCKER_API_PORT', 'directory', valid inputs are ['entryPoint', 'args', 'file_name']` 

.yml file
```
runs-on: self-hosted
steps:
- name: Create ROOT .env file
      uses: SpicyPizza/create-envfile@v1.0
      with:
        envkey_DOCKER_WEB_PORT: ${{ secrets.DOCKER_WEB_PORT }}
        envkey_DOCKER_API_PORT: ${{ secrets.DOCKER_API_PORT }}
        directory: ./
        file_name: .env
- name: Create WEB .env file
      uses: SpicyPizza/create-envfile@v1.0
      with:
        envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        directory: ./web-react
        file_name: .env
```
