### ISSUE TITLE
The documentation isn't very clear and I'm having trouble trying to figure it out.

### ISSUE THREAD

**Issue by ahmetskilinc** [SpicyPizza/create-envfile#14]
I currently have this in my workflow:

```yml
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    # - name: Run tests
    #   run: npm test
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_FIRESTORE_API_TOKEN: ${{ FIRESTORE_API_TOKEN }}
        file_name: .env
    - name: Build
      run: npm run react-build
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

Am I doing something wrong?
