### ISSUE TITLE
Warning: Unexpected input(s) 'envkey_XXX'

### ISSUE THREAD

**Issue by leolivier** [SpicyPizza/create-envfile#177]
Hi
Using the following step:
```yaml
  - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
        envkey_SMTP_HOST: ${{ vars.SMTP_HOST }}
        envkey_SMTP_PORT: ${{ vars.SMTP_PORT }}
        envkey_SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        envkey_SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        envkey_MAILDROP_INBOX: "test-maildropy-$${{github.job}}"
        envkey_SMTP_SSL_MODE: "SSL"
        directory: tests
        file_name: .env
        fail_on_empty: false
        sort_keys: false
```
I get this warning:
```
Warning: Unexpected input(s) 'envkey_FROM_ADDRESS', 'envkey_SMTP_HOST', 'envkey_SMTP_PORT', 'envkey_SMTP_USERNAME', 'envkey_SMTP_PASSWORD', 'envkey_MAILDROP_INBOX', 'envkey_SMTP_SSL_MODE', valid inputs are ['file_name', 'directory', 'fail_on_empty', 'sort_keys']
```
It looks like the .env file is properly generated as I don't have any key error afterward but why this warning?
