### ISSUE TITLE
Docker not found Error

### ISSUE THREAD

**Issue by Thamjith** [SpicyPizza/create-envfile#20]
The Error

```
Build container for action use: '/home/thamjith/actions-runner/nextjs-app/_actions/SpicyPizza/create-envfile/v1/Dockerfile'.
  Error: File not found: 'docker'
```

The yml file I'm using
```
name: Node.js CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
        directory: './'
        file_name: '.env'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run export
```
