### ISSUE TITLE
Github actions not adding .env file to source code

### ISSUE THREAD

**Issue by khannakshat7** [SpicyPizza/create-envfile#24]
I am facing issues with creating .env file. I am deploying my project using Google app engine. The project gets deployed but .env file is not created. Can you please help me with the issue.

This is my main.yaml file-
```
name: CI

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
  
jobs:
  create-envfile:
    runs-on: ubuntu-18.04
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: False
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_USER: ${{ secrets.USER }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          file_name: .env

  
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}

      - name: Publish app to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
```
Please check the output at https://github.com/khannakshat7/Elektra/actions/runs/888591866

**Comment by sumit4613** [comment]
@khannakshat7 

```
- name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: False
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_USER: ${{ secrets.USER }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          file_name: .env
```
          
`Make envfile` step should be inside build. 

Like this,

```
steps:
  - uses: actions/checkout@v2
  - name: Initialize Google Cloud SDK
    uses: zxyle/publish-gae-action@master
    with:
      service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      project_id: ${{ secrets.PROJECT_ID }}
      gae_variables: ${{ secrets.GAE_VARIABLES }}

  - name: Make envfile
    uses: SpicyPizza/create-envfile@v1
    with:
      ...

  - name: Publish app to Google App Engine
    run: |
      gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
      gcloud config set project ${{ secrets.PROJECT_ID }}
      gcloud -q app deploy app.yaml --promote      
```

Hope this resolves your issue.
