### ISSUE TITLE
Unexpected inputs error

### ISSUE THREAD

**Issue by 19peaches** [SpicyPizza/create-envfile#25]
When running this action I get the following error output:

```
Unexpected input(s) 'envkey_APP_ENV', 'envkey_APP_KEY', 'envkey_MIX_APP_URL', 'envkey_APP_URL', valid inputs are ['entryPoint', 'args', 'file_name']
```

My yaml looks like so:

```
- name: Generate .env file 
  uses: SpicyPizza/create-envfile@v1
  with:
    envkey_APP_ENV: staging
    envkey_APP_KEY: 
    envkey_MIX_APP_URL: https://staging.example.com
    envkey_APP_URL: https://staging.example.com 
- run: sudo chown -R $(id -u):$(id -g) .env
```

`APP_KEY` is initially empty and gets filled in later in a later `-run` command.

 Should these be nested under `args` or something?
