### ISSUE TITLE
Wrong documentation for v1.1

### ISSUE THREAD

**Issue by Hecsall** [SpicyPizza/create-envfile#26]
Hello, I was trying to use version 1.1 of this action, and after a lot of failed attempts to make it work, I noticed that there is a required parameter that the example on the readme does not cover.

Inside the `create-envfile.py` at line 18 there is:
```py
path = str(os.environ.get("INPUT_GITHUB_WORKSPACE"))
```
So it expects the user to manually input the GitHub workspace variable. If missing, that line will throw an error because it tries to output the env file into `None/directory/.env`.

To make it work it should be used like this:
```yaml
- name: Make envfile
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_SOME_VARIABLE: "test"
        directory: somedirectory
        github_workspace: ${{ github.workspace }}
```

Also, in the master branch, the title in the readme should say `SpicyPizza/create-envfile@master` (to use the master version) and not `SpicyPizza/create-envfile@v1.1`, which leads to confusion since the usage is a little different.

Hope it helps

**Comment by riboney** [comment]
@Hecsall Thank you so much! :100:

**Comment by Hecsall** [comment]
@riboney I saw the commit on your project, maybe I should have written the issue better.
The `github_workspace` parameter is only needed if you use the v1.1, instead if you use the `master` version you can omit that parameter, see examples below:

### **Using v1.1**
```yaml
- name: Make envfile
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_SOME_VARIABLE: "test"
        directory: somedirectory
        github_workspace: ${{ github.workspace }} # <-- this is needed in v.1.1
```

### **Using master**
```yaml
- name: Make envfile
      uses: SpicyPizza/create-envfile@master
      with:
        envkey_SOME_VARIABLE: "test"
        directory: somedirectory
        # here in master the github_workspace is not needed anymore
```
Now it should be clearer
