### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by yashkumarsharma** [SpicyPizza/create-envfile#28]
When I try to build a react-native App for iOS, I get an error.

`Error: Container action is only supported on Linux`

**Comment by AngelOnFira** [comment]
Can you post some information about your workflow file?

**Comment by yashkumarsharma** [comment]
Sorry for the delay, this is the original snippet which was causing this issue.
```
build-ios:
  needs: install
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_API_HOST: ${{ secrets.API_HOST }}
        envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        envkey_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
    - name: Install npm dependencies
      run: |
        npm install
    - name: Install pod dependencies
      run: |
        cd ios && pod install
    - name: Build app
      run: |
        xcodebuild -workspace App.xcworkspace -scheme App archive -archivePath App.xcarchive -allowProvisioningUpdates
        xcodebuild -exportArchive -archivePath ./App.xcarchive -exportPath . -exportOptionsPlist App/Info.plist
        mv App.ipa ../App.ipa
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: App.ipa
        path: ios/build/

```
