### ISSUE TITLE
Fail if secret is not defined

### ISSUE THREAD

**Issue by ErlanBazarov** [SpicyPizza/create-envfile#29]
I would like the workflow step to fail if the secret is not defined. But currently, it is not the case.
```
    - name: Make envfile for testing environment
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_STRIPE_SECRET_KEY: ${{ secrets.SECRET_VARIABLE }}

        file_name: .env
```
This still passes even if secrets.SECRET_VARIABLE is not defined
