### ISSUE TITLE
Provide an option to save all secrets into an .env file, instead of having to list them all as input parameters

### ISSUE THREAD

**Issue by knipknap** [SpicyPizza/create-envfile#3]
Through Github API, [it is possible to retrieve the name of all secrets at once](https://github.community/t/exporting-all-secrets-in-a-workflow-action/122365/3). It is also possible to [retrieve the value of a secret](https://docs.github.com/en/rest/reference/actions#get-a-repository-secret). That makes the workflow definition much easier, as it would eliminate the need to specify any ENVKEYs for secrets; the action could just dump all secrets instead.

Github API authentication is also painless, as every Github workflow [already provides an authentication token that can be used](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token).

**Comment by AngelOnFira** [comment]
Hmm this may be good functionality if you want to dump all of your secrets at once, but it would be overkill and potentially insecure if you only need a few. Maybe if an option was provided to dump all secrets, it could be handled differently?

Say something like
```
  inputs:
    file_name:
      description: 'The filename for the envfile'
      default: '.env'
    dump_all:
      description: 'Dump all secrets found in this projects Github Secrets'
      default: 'false'
```
