### ISSUE TITLE
env file not being created / GITHUB_WORKSPACE not set

### ISSUE THREAD

**Issue by speclechris** [SpicyPizza/create-envfile#45]
```
name: Create envfile

on: [ push ]

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_SOMETHING: something
```

I expected this to create the env file within my project directory e.g. `/home/runner/work/application-name/application-name/.env`

But I get the following:
`Creating file: /github/workspace/.env`

Only thing I can guess is GITHUB_WORKSPACE isn't set and it's defaulting to this path? 
`path = str(os.getenv("GITHUB_WORKSPACE", "/github/workspace"))`
