### ISSUE TITLE
Unable to create .env file

### ISSUE THREAD

**Issue by ianrussel** [SpicyPizza/create-envfile#52]
I got error related to file not created

            Creating file: /github/workspace/home/runner/work/ePricing/ePricing/.env
            File "/opt/action/create-envfile.py", line 47, in <module>
             with open(full_path, "w") as text_file:
             FileNotFoundError: [Errno 2] No such file or directory: '/github/workspace/home/runner/work/ePricing/ePricing/.env'

Here's the workflow

             
              build:
                 runs-on: ubuntu-latest
                 steps:
                      - uses: actions/checkout@v2
                      - uses: SpicyPizza/create-envfile@main
                        with:
                             envkey_DEBUG: false
                             envkey_DB_SERVER: ${{ secrets.DB_SERVER }}
                             directory: ePricing/
                             file_name: .env
                             fail_on_empty: false

Any ideas?

**Comment by ianrussel** [comment]
Why go to complexity when we can just use simpler and working solution :)

     jobs:    
         create-envfile:
               runs-on: ubuntu-latest
               steps:
                  - name: Env create
                    run: |
                       touch .env
                            echo SECRET_KEY="q^p9eee+l$#mh6#c@#^eqno!j-e#8-$aq6(z9xbrqwep53dejiomv#" >> .env
                            ..................

**Comment by AxelLR992** [comment]
For anyone else facing this issue, I was able to fix it synchronising my files first using checkout. To be clear, this is what I've done:

**Before**
```yml
jobs:
  create-env:
    name: Create env file
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:  
          [My variables]
```

**After**
```yml
jobs:
  create-env:
    name: Create env file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          [My variables]
```
