### ISSUE TITLE
How can I create .env file with my own custom name?

### ISSUE THREAD

**Issue by khayargoli** [SpicyPizza/create-envfile#54]
How can I create .env file with my own custom name? for example for staging I want to create .staging.env file or for production .prod.env?

Can I do this?

**Comment by akmal2409** [comment]
I believe putting following in with block
file_name: .env.test

**Comment by AngelOnFira** [comment]
Yes, from the readme:

```yml
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        file_name: .staging.env # <-- Here
```

Please reopen if this doesn't work!
