### ISSUE TITLE
$GITHUB_WORKSPACE is not always the hard coded path

### ISSUE THREAD

**Issue by jheckman-rt** [SpicyPizza/create-envfile#7]
I'm trying to use the environment file that I create in a subsequent step and it's failing because the python script is hard coded to put the file in path = "/github/workspace"

I'd like to create a change where instead of looking at that, it gets the GITHUB_WORKSPACE environment variable and sets it to that instead.

**Comment by sumit4613** [comment]
@jheckman-rt If I'm not wrong you want to create your .env file in some other directory rather than in the root directory. If that's the case please use ` SpicyPizza/create-envfile@master` in your GitHub actions and checkout about `directory` in the readme file.

Please let me know if I understood something wrong.

**Comment by jheckman-rt** [comment]
I believe you misunderstood.  The file is being put in "/github/workspace" path (hard coded in your action) which is not always present.  We need to allow that to be pulled from the environment so it can be put elsewhere.  Github actions updated and no longer uses that hard coded path anymore.

**Comment by sumit4613** [comment]
I really misunderstood your problem sorry about that.

> Github actions updated and no longer uses that hard coded path anymore.
Would you like to share any link related to this update. Thanks!

**Comment by jheckman-rt** [comment]
Well now I cannot figure out where I read that!  However, I want to share with you how I'm using this action - I forked it to make my changes and get it to work (jheckman-rt/create-envfile@v1.1).  I pasted it below so you can see exactly what I'm doing (thought it might be helpful).

I changed line 18 in the src/create-envfile.py to `path = str(os.environ.get("INPUT_GITHUB_WORKSPACE"))
` instead of /github/workspace and that solved my problem.  For whatever reason, the action I created does not use /github/workspace as the default workspace.  It creates a different path (https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables - see GITHUB_WORKSPACE env variable).

Thoughts?

```
on:
  release:
    types: [published]

name: Apply Flyway Migration to Dev

jobs:
  flyway-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Published
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}

      - name: Pulls env variables from file
        id: dotenv
        uses: falti/dotenv-action@v0.2.5
        with:
          path: env/.env.dev
      
      - name: Make envfile for Dev
        uses: jheckman-rt/create-envfile@v1.1
        with:
          envkey_USER: ${{ steps.dotenv.outputs.user }}
          envkey_URL: ${{ steps.dotenv.outputs.url }}
          envkey_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
          directory: env
          file_name: .env.flyway

      - name: Apply migration
        run: docker-compose up -d

      - name: Log viewing
        run: docker-compose logs
```
